apps/msg_app/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'users/show/(?P<number>[0-9]{1,})$', views.show, name="show"),
    url(r'process_message$', views.process_message, name="process_message"),
    url(r'process_comment$', views.process_comment, name="process_comment")
]

apps/user_app/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"), 
    #url(r'users$', views.index, name="index"), 
    url(r'edit$', views.edit, name="edit"), 
    url(r'edit/(?P<number>[0-9]{1,})$', views.edit_admin, name="edit_admin"), 
    url(r'update_my_info/(?P<number>[0-9]{1,})$', views.update_my_info, name="update_my_info"), 
    url(r'update_my_description/(?P<number>[0-9]{1,})$', views.update_my_description, name="update_my_description"),
    url(r'update_my_password/(?P<number>[0-9]{1,})$', views.update_my_password, name="update_my_password"),
    #url(r'users/show/(?P<number>[0-9]{1,})$', views.show, name="show"), #this is in msg_app...
    url(r'register$', views.register, name="register"), 
    url(r'users/new$', views.new, name="new"), 
    url(r'create$', views.create, name="create"), 
    url(r'signin$', views.sign_in, name="sign_in"), 
    url(r'verify$', views.verify_sign_in, name="verify_sign_in"), 
    url(r'logout$', views.log_out, name="log_out"),
    url(r'delete/(?P<number>[0-9]{1,})$', views.delete, name="delete"),
    url(r'dashboard$', views.dashboard, name="dashboard"), 
    url(r'dashboard/admin$', views.dashboard_admin, name="dashboard_admin")
]

userdash_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.user_app.models import User as U
class UAdmin(admin.ModelAdmin):
    pass
admin.site.register(U, UAdmin)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.user_app.urls', namespace='users')), 
    url(r'^', include('apps.msg_app.urls', namespace='message')), 
    url(r'^users/', include('apps.user_app.urls', namespace='users')), 
    url(r'^message/', include('apps.msg_app.urls', namespace='message'))
]

apps/user_app/models.py
from __future__ import unicode_literals
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator, RegexValidator
from django.db import models

# Create your models here.
# EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
# NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')
NAME_REGEX = r'^[A-Za-z]\w+$'

def validateLengthGreaterThanTwo(value):
    if len(value) < 3:
        raise ValidationError(
            '{} must be longer than: 2 characters'.format(value)
        )

class User(models.Model):
    # Using choices because this data is static and won't really change. 
    # Otherwise, it would be better to create another db table with a foreign key. 
    USER_LEVEL_CHOICES = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
        (6,6),
        (7,7),
        (8,8),        
        (9,9)
    )
    first_name = models.CharField(max_length=255, validators=[validateLengthGreaterThanTwo, RegexValidator(regex=NAME_REGEX)])
    last_name = models.CharField(max_length=255, validators=[validateLengthGreaterThanTwo, RegexValidator(regex=NAME_REGEX)])
    email = models.EmailField(validators=[EmailValidator()])
    password = models.CharField(max_length=100, validators=[validateLengthGreaterThanTwo])
    # user_level = models.IntegerField(default=1)
    user_level = models.IntegerField(choices = USER_LEVEL_CHOICES, default=1)
    description = models.CharField(max_length=1000, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/user_app/forms.py
from django import forms
from .models import User

class RegistrationForm(forms.Form):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=100)
	last_name = forms.CharField(max_length=100)
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)
	confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)

class RegisterForm(forms.ModelForm):
	# Confirm pword code from Savai Maheshwari at https://stackoverflow.com/questions/34609830/django-modelform-how-to-add-a-confirm-password-field
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)
	confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)
	class Meta:
		model = User
    #   fields = '__all__'
		fields = ['email','first_name','last_name','password']
	def clean(self):
		cleaned_data = super(RegisterForm, self).clean()
		
		password = cleaned_data.get("password")
		confirm_password = cleaned_data.get("confirm_password")
		
		if password != confirm_password:
			self.add_error('confirm_password', "Password does not match.")

		email = cleaned_data.get('email')
		users = User.objects.filter(email=email)
		if len(users) != 0:
			self.add_error('email', "Email address is already registered in this system. Please try again.")
		return cleaned_data

class SignInForm(forms.Form):
	email = forms.EmailField()
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)

class SignIn_Form(forms.ModelForm):
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['email','password']
	def clean(self):
		cleaned_data = super(SignIn_Form, self).clean()	
		email = cleaned_data.get('email')
		password = cleaned_data.get("password")
		users = User.objects.filter(email=email)		
		if len(users) == 0:
			self.add_error('email', "Email address is not registered in this system. Please try again.")
		users = User.objects.filter(email=email, password=password)		
		if len(users) == 0:
			self.add_error('password', "Email address and password combo is not registered in this system. Please try again.")
		return cleaned_data

class UpdateInfoForm(forms.Form):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=100)
	last_name = forms.CharField(max_length=100)

class UpdateInfo_Form(forms.ModelForm):
	class Meta: 
		model = User
		fields = ['email', 'first_name', 'last_name']
	def clean(self):
		cleaned_data = super(UpdateInfo_Form, self).clean()
		email = cleaned_data.get('email')
		first_name = cleaned_data.get('first_name')
		last_name = cleaned_data.get('last_name')
		user_id = self.instance.pk
		users = User.objects.filter(email=email)
		if len(users) != 0:
			if users[0].id != user_id:
				self.add_error('email', "Email address is already registered in this system. Please try again.")
			else:
				pass
		return cleaned_data

class UpdateInfoAdminForm(forms.Form):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=100)
	last_name = forms.CharField(max_length=100)
	user_level = forms.ChoiceField()

class UpdateInfoAdmin_Form(forms.ModelForm):
	class Meta: 
		model = User
		fields = ['email', 'first_name', 'last_name', 'user_level']
		# fields = ['email', 'first_name', 'last_name']
	def clean(self):
		cleaned_data = super(UpdateInfoAdmin_Form, self).clean()
		email = cleaned_data.get('email')
		first_name = cleaned_data.get('first_name')
		last_name = cleaned_data.get('last_name')
		user_level = cleaned_data.get('user_level')
		user_id = self.instance.pk
		if len(users) != 0:
			if users[0].id != user_id:
				self.add_error('email', "Email address is already registered in this system. Please try again.")
			else:
				pass
		return cleaned_data

class UpdatePasswordForm(forms.Form):
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)
	confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)

class UpdatePassword_Form(forms.ModelForm):
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)
	confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)	
	class Meta: 
		model = User
		fields = ['password']
	def clean(self):
		cleaned_data = super(UpdatePassword_Form, self).clean()
		password = cleaned_data.get("password")
		confirm_password = cleaned_data.get("confirm_password")
		if password != confirm_password:
			self.add_error('confirm_password', "Password does not match.")
		return cleaned_data

class UpdateDescriptionForm(forms.Form):
	# description = forms.CharField(max_length=1000)
	description = forms.CharField(widget=forms.Textarea)

class UpdateDescription_Form(forms.ModelForm):
	class Meta: 
		model = User
		fields = ['description']		
	def clean(self):
		cleaned_data = super(UpdateDescription_Form, self).clean()
		description = cleaned_data.get("description")
		return cleaned_data

apps/user_app/views.py
from __future__ import unicode_literals
from django.shortcuts import render, reverse, redirect
from forms import RegistrationForm, RegisterForm, SignInForm, SignIn_Form, UpdateInfoForm, UpdateInfo_Form, UpdateInfoAdminForm, UpdateInfoAdmin_Form, UpdatePasswordForm, UpdatePassword_Form, UpdateDescription_Form
from .models import User
from django.contrib import messages 

# Create your views here.
def index(request):
    return render(request, "user_app/index.html")

# To create a new record, first render the register.html page. Then call the create route, which redirects to a landing page route, such as users:index.
def register(request):
    context = {
        'myregistrationform': RegistrationForm()
    }    
    return render(request, "user_app/register.html", context)
def new(request):
    context = {
        'myregistrationform': RegistrationForm()
    }    
    return render(request, "user_app/new.html", context)
def create(request):
    # this is the method that actually creates a user who is registering itself, or who is being registered by an admin
    if request.method == "POST":
        bound_form = RegisterForm(request.POST)
        if bound_form.is_valid():
            bound_form.save()
            users = User.objects.all()
            if len(users) == 1:
                users[0].user_level = 9
                users[0].save()
            else:
                users[0].first_name, users[0].last_name
            user = User.objects.get(email=request.POST['email'], password=request.POST['password'])
            if "user_id" not in request.session:
                request.session['user_id'] = user.id
                request.session['user_level'] = user.user_level
            if request.session['user_level'] >= 9:
                return redirect(reverse("users:dashboard_admin")) 
            else:
                return redirect(reverse("users:dashboard")) 
        else:
            context = {
                'myregistrationform': bound_form
            }
            return render(request, "user_app/register.html", context) 
def sign_in(request):
    context = {
        'mysigninform': SignInForm()
    }    
    return render(request, "user_app/signin.html", context)
def verify_sign_in(request):
    if request.method == "POST":
        bound_form = SignIn_Form(request.POST)
        if bound_form.is_valid():
            # errors should be checked for elsewhere with validator methods in models.py and forms.py. Thus, using get instead of filter here.
            user = User.objects.get(email=request.POST['email'], password=request.POST['password'])
            request.session['user_id'] = user.id
            request.session['user_level'] = user.user_level
            if request.session['user_level'] >= 9:
                return redirect(reverse("users:dashboard_admin")) 
            else:
                return redirect(reverse("users:dashboard")) 
        else: 
            context = {
                'mysigninform': bound_form
            }
            return render(request, "user_app/signin.html", context)       

def log_out(request):
    request.session.clear()
    return redirect(reverse("users:index")) 

def edit(request):
    user =  User.objects.get(id=request.session['user_id'])
    myupdateinfoform = UpdateInfo_Form(instance=user)
    myupdatepasswordform = UpdatePasswordForm()
    myupdatedescriptionform = UpdateDescription_Form(instance=user)
    context = {
        'user':User.objects.get(id=request.session['user_id']),
        'myupdateinfoform': myupdateinfoform,
        'myupdatepasswordform': myupdatepasswordform, 
        'myupdatedescriptionform':myupdatedescriptionform
    }
    return render(request, "user_app/edit.html", context)
def edit_admin(request, number):
    user =  User.objects.get(id=number)
    myupdateinfoform = UpdateInfoAdmin_Form(instance=user)
    myupdatepasswordform = UpdatePasswordForm()
    myupdatedescriptionform = UpdateDescription_Form(instance=user)
    context = {
        'user':User.objects.get(id=number),
        'myupdateinfoform': myupdateinfoform,
        'myupdatepasswordform': myupdatepasswordform, 
        'myupdatedescriptionform':myupdatedescriptionform
    }
    return render(request, "user_app/edit_admin.html", context)
def update_my_info(request, number):
    if request.session['user_level']>=9 or request.session['user_id'] == int(number):
        if request.method == "POST":
            user = User.objects.get(id=number)
            my_bound_form = UpdateInfo_Form(request.POST, instance=user)

            if my_bound_form.is_valid():
                my_bound_form.save()
                context = {
                    'users':User.objects.all()
                }
                return render(request, "user_app/dashboard_admin.html", context)
            else:            
                context = {
                    'user': user,
                    'myupdateinfoform': my_bound_form,
                    'myupdatepasswordform': UpdatePasswordForm(), 
                    'myupdatedescriptionform':UpdateDescription_Form(instance=user)
                }
                return render(request, "user_app/edit_admin.html", context)
    else:
        context = {
            'users':User.objects.all()
        }
        return render(request, "user_app/dashboard.html", context) 
def update_my_description(request, number):
    if request.session['user_level']>=9 or request.session['user_id'] == int(number):
        if request.method == "POST":
            user = User.objects.get(id=number)
            my_bound_form = UpdateDescription_Form(request.POST, instance=user)
            if my_bound_form.is_valid():
                my_bound_form.save()
                context = {
                    'users':User.objects.all()
                }
                return render(request, "user_app/dashboard_admin.html", context)
            else:                 
                context = {
                    'user': user,
                    'myupdateinfoform': UpdateInfo_Form(instance=user),
                    'myupdatepasswordform': UpdatePasswordForm(), 
                    'myupdatedescriptionform':my_bound_form
                }
                return render(request, "user_app/edit_admin.html", context)
    else:
        context = {
            'users':User.objects.all()
        }
        return render(request, "user_app/dashboard.html", context)
def update_my_password(request, number):
    if request.method == "POST":
        user = User.objects.get(id=number)
        my_bound_form = UpdatePassword_Form(request.POST, instance=user)
        if my_bound_form.is_valid():
            my_bound_form.save()   
            context = {
                'users':User.objects.all()
            }
            return render(request, "user_app/dashboard_admin.html", context)
        else:                 
            context = {
                'user': user,
                'myupdateinfoform': UpdateInfo_Form(instance=user),
                'myupdatepasswordform': my_bound_form, 
                'myupdatedescriptionform':UpdateDescription_Form(instance=user)
            }
            return render(request, "user_app/edit_admin.html", context)
    else:
        context = {
            'users':User.objects.all()
        }
        return render(request, "user_app/dashboard.html", context)

def delete(request, number):
    if request.session['user_level'] >=9:
        if number != "17" and number != "18" and number != "19" and number != "20":
            User.objects.get(id=number).delete()
    context = {
        'users':User.objects.all()
    }
    return render(request, "user_app/dashboard_admin.html", context)

def dashboard(request):
    context = {
        'users':User.objects.all()
    }
    return render(request, "user_app/dashboard.html", context)
def dashboard_admin(request):
    context = {
        'users':User.objects.all()
    }
    return render(request, "user_app/dashboard_admin.html", context)

def show(request, number):
    return render(request, "msg_app/messages.html")

apps/user_app/templates/user_app/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatBoard</title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'user_app/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
    <script>
        $(document).on('click', '.confirm-delete', function(){
            return confirm('Are you sure you want to delete this?');
        })
    </script>
</head>
<body>
    <div class="header">
        {% if request.session.user_level >= 9 %}
            <span class="header_left_login"><h2>ChatBoard</h2><h3><a href="{% url 'users:dashboard_admin' %}">Dashboard</a></h3><h3><a href="{% url 'users:edit' %}">Profile</a></h3></span>
        {% endif %}
        {% if request.session.user_level < 9 %}
            <span class="header_left_login"><h2>ChatBoard</h2><h3><a href="{% url 'users:dashboard' %}">Dashboard</a></h3><h3><a href="{% url 'users:edit' %}">Profile</a></h3></span>
        {% endif %}
        <span class="header_right_login"><h3><a href="{% url 'users:log_out' %}">Log Off</a></h3></span>
    </div>
    <div class="main_reg">
        <div class="main_reg_left"><h3>Manage Users</h3></div>
        <div class="main_reg_right"></div><br><br>
        <table class="table-striped">
            <thead class="thead-inverse">
                <tr>
                    <th width="50px">ID</th>
                    <th width="218px">User ChatBoard</th>
                    <th width="218px">Email</th>
                    <th width="200px">Created_at</th>
                    <th width="100px">User_level</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td width="50px">{{user.id}}</td>
                    <td width="218px"><a href="{% url 'message:show' user.id %}">{{user.first_name}} {{user.last_name}}</a></td>
                    <td width="218px">{{user.email}}</td>
                    <td width="200px">{{user.created_at}}</td>
                    <td width="100px">{{user.user_level}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>    
    </div>
</body>
</html>

apps/user_app/templates/user_app/dashboard_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatBoard</title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'user_app/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
    <script>
        $(document).on('click', '.confirm-delete', function(){
            return confirm('Are you sure you want to delete this?\nFor this demo, users with ID\'s 17, 18, 19, and 20 cannot be deleted.\nTry to make and delete your own user!');
        })
    </script>
</head>
<body>
    <div class="header">
        {% if request.session.user_level >= 9 %}
            <span class="header_left_login"><h2>ChatBoard</h2><h3><a href="{% url 'users:dashboard_admin' %}">Dashboard</a></h3><h3><a href="{% url 'users:edit' %}">Profile</a></h3></span>
        {% endif %}
        {% if request.session.user_level < 9 %}
            <span class="header_left_login"><h2>ChatBoard</h2><h3><a href="{% url 'users:dashboard' %}">Dashboard</a></h3><h3><a href="{% url 'users:edit' %}">Profile</a></h3></span>
        {% endif %}
        <span class="header_right_login"><h3><a href="{% url 'users:log_out' %}">Log Off</a></h3></span>
    </div>
    <div class="main_reg">
        <div class="main_reg_left"><h3>Manage Users</h3></div>
        <div class="main_reg_right"><a class="main_reg_new_a" href={% url 'users:new' %}><button class='btn btn-primary'>Add new</button></a></div><br><br>
        <table class="table-striped">
            <thead class="thead-inverse">
                <tr>
                    <th width="50px">ID</th>
                    <th width="218px">User ChatBoard</th>
                    <th width="218px">Email</th>
                    <th width="200px">Created_at</th>
                    <th width="100px">User level</th>
                    <th width="150px">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td width="50px">{{user.id}}</td>
                    <td width="218px"><a href="{% url 'message:show' user.id %}">{{user.first_name}} {{user.last_name}}</a></td>
                    <td width="218px">{{user.email}}</td>
                    <td width="200px">{{user.created_at}}</td>
                    <td width="100px">{{user.user_level}}</td>
                    <!-- delete confirmation code from: https://stackoverflow.com/questions/37398416/django-delete-confirmation -->
                    <td width="150px"><a href="users/edit/{{user.id}}">edit</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="confirm-delete" href="users/delete/{{user.id}}">remove</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>    
    </div>
</body>
</html>

apps/user_app/templates/user_app/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatBoard</title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'user_app/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
    <div class="header">
        {% if request.session.user_level >= 9 %}
            <span class="header_left_login"><h2>ChatBoard</h2><h3><a href="{% url 'users:dashboard_admin' %}">Dashboard</a></h3><h3><a href="{% url 'users:edit' %}">Profile</a></h3></span>
        {% endif %}
        {% if request.session.user_level < 9 %}
            <span class="header_left_login"><h2>ChatBoard</h2><h3><a href="{% url 'users:dashboard' %}">Dashboard</a></h3><h3><a href="{% url 'users:edit' %}">Profile</a></h3></span>
        {% endif %}
        <span class="header_right_login"><h3><a href="{% url 'users:log_out' %}">Log Off</a></h3></span>
    </div>
    <div class="main_reg">
            <div class="main_reg_left"><h3>Add new user</h3></div>
            <div class="main_reg_right"><a class="main_reg_new_a" href={% url 'users:dashboard_admin' %}><button class='btn btn-primary'>Return to Dashboard</button></a></div><br>
            <form class="" action={% url 'users:create' %} method="post">
                {% csrf_token %}
                {{ myregistrationform.as_p }}
                <input type="submit" name="" value="Create" class='btn btn-primary'>
            </form>
            <br>
        </div>
</body>
</html>

apps/user_app/templates/user_app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatBoard</title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'user_app/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
    <div class="header">
        <span class="header_left"><h2>ChatBoard</h2><h3><a href="{% url 'users:index' %}">Home</a></h3></span>
        <span class="header_right"><h3><a href="{% url 'users:sign_in' %}">Sign In</a></h3></span>
    </div>
    <div class="main_reg">
        <!-- {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %} -->
        <h3>Register</h3><br>
        <form class="" action={% url 'users:create' %} method="post">
            {% csrf_token %}
            {{ myregistrationform.as_p }}
            <input type="submit" name="" value="Register" class='btn btn-primary'>
        </form>
        <br>
        <a href="{% url 'users:sign_in' %}">Already have an account? Login.</a>
    </div>
</body>
</html>

apps/user_app/templates/user_app/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatBoard</title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'user_app/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
    <div class="header">
        <span class="header_left"><h2>ChatBoard</h2><h3><a href="{% url 'users:index' %}">Home</a></h3></span>
        <span class="header_right"><h3><a href="{% url 'users:sign_in' %}">Sign In</a></h3></span>
    </div>
    <div class="main_reg">
        <!-- {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %} -->
        <h3>SignIn</h3><br>
        <form class="" action={% url 'users:verify_sign_in' %} method="post">
            {% csrf_token %}
            {{ mysigninform.as_p }}
            <input type="submit" name="" value="Sign In" class='btn btn-primary'>
        </form>
        <br>
        <a href="{% url 'users:register' %}">Don't have an account? Register.</a>
        <div class="loginTips">
            <h6>Login as an admin</h6> 
            <p><span>Email:</span>user1@email.com</p>
            <p><span>Password:</span>123</p>
            <h6>Login as a non-admin user</h6> 
            <p><span>Email:</span>user2@email.com</p>
            <p><span>Password:</span>123</p>
            <h6>Or, <a href="{% url 'users:register' %}"></a>register your own user!</a></h6>
        </div>
    </div>
</body>
</html>